# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "sentia-capistrano-gitflow"
  s.version = "1.4.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Joshua Nichols", "Mario Visic"]
  s.date = "2012-06-04"
  s.description = "Capistrano recipe for a deployment workflow based on git tags. This gem was originally created by Joshua Nichols and modified by Mario Visic at Sentia Australia."
  s.email = "mario.visic@sentia.com.au"
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/sentia/capistrano/gitflow.rb",
    "lib/sentia/capistrano/gitflow/natcmp.rb",
    "recipes/gitflow_recipes.rb",
    "sentia-capistrano-gitflow.gemspec"
  ]
  s.homepage = "https://github.com/Sentia/git-deployment"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "Capistrano recipe for a deployment workflow based on git tags. This gem was originally created by Joshua Nichols and modified by Mario Visic at Sentia Australia."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<sentia-capistrano-gitflow>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_runtime_dependency(%q<capistrano>, [">= 0"])
      s.add_runtime_dependency(%q<stringex>, [">= 0"])
    else
      s.add_dependency(%q<sentia-capistrano-gitflow>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<capistrano>, [">= 0"])
      s.add_dependency(%q<stringex>, [">= 0"])
    end
  else
    s.add_dependency(%q<sentia-capistrano-gitflow>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<capistrano>, [">= 0"])
    s.add_dependency(%q<stringex>, [">= 0"])
  end
end

